stages:
  - test

test:
  stage: test
  image: gcc:latest
  before_script:
    - apt-get update && apt-get install -y make g++ 
  script:
    - make clean
    - make test CFLAGS="--coverage" CXXFLAGS="--coverage" LDFLAGS="--coverage"
    - gcovr --print-summary
  coverage: /^TOTAL.*\s+(\d+\%)$/
